//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentAccountingApp.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.TechnicalMaintenance = new HashSet<TechnicalMaintenance>();
        }
    
        public int idEquipment { get; set; }
        public string EquipmentName { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<System.DateTime> DateOfDecommissioning { get; set; }
        public Nullable<int> idWorkshop { get; set; }
        public Nullable<int> idTechnicalSpecifications { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<int> idAdmin { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Status Status { get; set; }
        public virtual TechnicalSpecifications TechnicalSpecifications { get; set; }
        public virtual Workshop Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnicalMaintenance> TechnicalMaintenance { get; set; }
    }
}
