//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentAccountingApp.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalMaintenance
    {
        public int idTechnicalMaintenance { get; set; }
        public Nullable<int> idEquipment { get; set; }
        public Nullable<System.DateTime> DateOfMaintenance { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual TypeMaintenance TypeMaintenance { get; set; }
    }
}
